- name: Enable caddy repo
  community.general.copr:
    state: enabled
    name: '@caddy/caddy'

- name: Install caddy
  yum:
    name:
      - caddy
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Template Caddyfile
  ansible.builtin.template:
    src: files/Caddyfile.jinja
    dest: /etc/caddy/Caddyfile
  register: caddyfile

- name: Start caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  when: caddyfile.changed