- name: Docker repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: start docker
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    state: started