- name: copy kubernetes repo
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  register: kubernetes

- name: Install kubectl, helm and pip
  yum:
    name:
      - kubectl
      - curl
      - helm
      - pip
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: install and configure doctl if kubeconfig is not provided, and connect kubectl to k8 cluster
  when: lookup('ansible.builtin.fileglob', 'files/kubeconfig.yaml') == []
  block:
    - name: download doctl
      get_url:
        url: https://github.com/digitalocean/doctl/releases/download/v1.92.0/doctl-1.92.0-linux-amd64.tar.gz
        dest: /root/doctl.tar.gz

    - name: unar doctl and move to path
      unarchive:
        src: /root/doctl.tar.gz
        dest: /usr/local/bin
        remote_src: true

    - name: init doctl
      command:
        cmd: doctl auth init
        creates: /var/lib/jenkins/.config/doctl/config.yaml
      become_user: jenkins
      environment:
        DIGITALOCEAN_ACCESS_TOKEN: "{{ digitalocean_token }}"

    - name: get kubectl config
      become_user: jenkins
      command:
        cmd: doctl kubernetes cluster kubeconfig save {{ k8_id }}
        creates: /var/lib/jenkins/.kube/config

    - name: Get kubeconfig if not present on host
      ansible.builtin.slurp:
        src: /var/lib/jenkins/.kube/config
      register: kubeconfig

    - name: copy kubeconfig to localhost
      delegate_to: localhost
      become: false
      copy:
        dest: roles/jenkins/files/kubeconfig.yaml
        content: "{{ kubeconfig['content'] | b64decode }}"
    # - name: copy kubeconfig to localhost
      # delegate_to: localhost
      # become: false
      # command:
      #   # cmd: "cat > files/kubeconfig.yaml << EOF\n{{ kubeconfig['content'] | b64decode }}EOF"
        # creates: files/kubeconfig.yaml

# end of block

- name: upload kubectl config from local
  when: lookup('ansible.builtin.fileglob', 'files/kubeconfig.yaml') != []
  block:
    - name: make sure .kube folder exists
      file:
        path: /var/lib/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins

    - name: upload kubectl config
      copy:
        src: files/kubeconfig.yaml
        dest: /var/lib/jenkins/.kube/config
      become_user: jenkins

- name: install required pip packages
  pip:
    name:
      - kubernetes

- name: install required pip packages on host
  become: false
  delegate_to: localhost
  pip:
    name:
      - kubernetes

- name: Add stable caddy chart repo
  become_user: jenkins
  kubernetes.core.helm_repository:
    name: ingress-caddy
    repo_url: "https://caddyserver.github.io/ingress/"
  register: repo

- debug:
    msg: "{{ repo.command }}"
  when: repo.changed

- name: Deploy caddy ingress controller with helm
  register: caddy_ingress
  until: caddy_ingress is success
  delay: 6
  retries: 10
  become_user: jenkins
  kubernetes.core.helm:
    name: ingress-controller
    update_repo_cache: True
    chart_ref: ingress-caddy/caddy-ingress-controller
    release_namespace: caddy-system
    create_namespace: true
    kubeconfig: /var/lib/jenkins/.kube/config
    values:
      ingressController.config.email: "{{ certificate_email }}"
      ingressController.config.onDemandTLS: true

- name: Create ingress
  become_user: jenkins
  register: ingress
  until: ingress is success
  delay: 6
  retries: 10
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: minimal-ingress
        namespace: caddy-system
        annotations:
          kubernetes.io/ingress.class: caddy
      spec:
        defaultBackend:
          service:
            name: tea-svc
            port:
              number: 80

- name: Get docker registry
  ansible.builtin.slurp:
    src: /var/lib/jenkins/.docker/config.json
  register: dockerconfigjson

- name: Create registry secret
  become_user: jenkins
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: regcred
        namespace: default
      data:
        .dockerconfigjson: "{{ dockerconfigjson['content'] }}"
      type: kubernetes.io/dockerconfigjson

- name: Get load balancer info
  delegate_to: localhost
  become: false
  set_fact:
    k8_services: "{{ query('kubernetes.core.k8s', kind='Service', namespace='caddy-system', kubeconfig='roles/jenkins/files/kubeconfig.yaml') }}"

- name: Get loadbalancer ip
  delegate_to: localhost
  become: false
  set_fact:
    k8_loadbalancer_ip: "{{ k8_services[0]['status']['loadBalancer']['ingress'][0]['ip']  }}"

- name: Get dns record id if any
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records list {{ domain_name }} | grep k8 | cut -d \" \" -f 1  > record_id"'
    creates: record_id

- name: Get dns wildcard record id if any
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records list {{ domain_name }} | grep "*.k8" | cut -d \" \" -f 1  > wildcard_record_id"'
    creates: wildcard_record_id

- name: set record_id fact
  delegate_to: localhost
  become: false
  set_fact:
    record_id: "{{ lookup('file', 'record_id') }}"

- name: set wildcard_record_id fact
  delegate_to: localhost
  become: false
  set_fact:
    wildcard_record_id: "{{ lookup('file', 'wildcard_record_id') }}"

- name: create dns record
  when: record_id == ''
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records create {{ domain_name }} --record-name k8 --record-type A --record-ttl 60 --record-data {{ k8_loadbalancer_ip }} > created_record"'
    creates: created_record

- name: update dns record
  when: record_id != ''
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records update {{ domain_name }}  --record-id {{ record_id }} --record-name k8 --record-type A --record-ttl 60 --record-data {{ k8_loadbalancer_ip }} > created_record"'
    creates: created_record

- name: create wildcard record
  when: wildcard_record_id == ''
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records create {{ domain_name }} --record-name *.k8 --record-type A --record-ttl 60 --record-data {{ k8_loadbalancer_ip }} > created_wildcard_record"'
    creates: created_wildcard_record

- name: update wildcard record
  when: wildcard_record_id != ''
  become: false
  delegate_to: localhost
  command:
    cmd: 'sh -c "doctl compute domain records update {{ domain_name }} --record-id {{ record_id }} --record-name *.k8 --record-type A --record-ttl 60 --record-data {{ k8_loadbalancer_ip }} > created_wildcard_record"'
    creates: created_wildcard_record
