- name: Add apt keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://pkg.jenkins.io/debian-stable/jenkins.io.key
    - https://dl.cloudsmith.io/public/caddy/stable/gpg.key

- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - deb https://download.docker.com/linux/ubuntu focal stable
    - deb http://pkg.jenkins.io/debian-stable binary/
    - deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main


- name: Install java, caddy, jenkins and other packages
  apt:
    pkg:
      - openjdk-17-jdk
      - openjdk-17-jre
      - caddy
      - jenkins
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: Update apt and install docker packages
  apt:
    name:
      - docker-ce
      - docker-compose
    state: latest
    update_cache: true
  register: apt_status2
  until: apt_status2 is success
  delay: 6
  retries: 10

- name: start docker
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    state: started

- name: copy jenkins config
  copy:
    src: files/jenkins.service
    dest: /lib/systemd/system/jenkins.service
  register: jenkinsfile

- name: Template CasC
  ansible.builtin.template:
    src: files/jenkins.casc.yml.jinja
    dest: /var/lib/jenkins/casc.yml
  register: casc

- name: copy jobs
  copy:
    src: files/job-dsl.groovy
    dest: /var/lib/jenkins/job_dsl.groovy
  register: jobs

- name: Start jenkins
  ansible.builtin.systemd:
    daemon_reload: yes
    name: jenkins
    state: restarted
  when: jenkinsfile.changed

- name: Template Caddyfile
  ansible.builtin.template:
    src: files/Caddyfile.jinja
    dest: /etc/caddy/Caddyfile
  register: caddyfile

- name: Start caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
  when: caddyfile.changed

- name: get jenkins initial password
  command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: initialPassword

- name: Wait for Jenkins to be reachable
  uri:
    url: https://jenkins.{{ domain_name }}/login
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install  plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    state: present
    url_username: admin
    url_password: "{{ initialPassword.stdout }}"
    url: https://jenkins.{{ domain_name }}
  loop:
    - configuration-as-code
    - credentials
    - github
    - job-dsl
    - role-strategy
    - script-security
    - ws-cleanup
  register: plugins

- name: add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: true
  register: user_group

- name: restart jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
  when: plugins.changed or jobs.changed

- name: enable plugins
  community.general.jenkins_plugin:
    name: "{{ item }}"
    state: enabled
    url_username: admin
    url_password: "{{ initialPassword.stdout }}"
    url: https://jenkins.{{ domain_name }}
  loop:
    - configuration-as-code
    - credentials
    - github
    - job-dsl
    - role-strategy
    - script-security
    - ws-cleanup


- name: make sure /var/lib/jenkins/whanos_images exists
  ansible.builtin.file:
    path: /var/lib/jenkins/whanos_images
    state: directory
    mode: '0755'

- name: Copy whanos image build files
  ansible.builtin.copy:
    src: "files/whanos_images/{{ item }}"
    dest: /var/lib/jenkins/whanos_images
  loop:
    - befunge
    - c
    - java
    - javascript
    - python

- name: Copy detect_project.py to /bin/detect_project
  ansible.builtin.copy:
    src: "files/detect_project.py"
    dest: /bin/detect_project
