- name: yum update
  yum:
    name: '*'
    state: latest

- name: setup docker and caddy
  include_tasks:
    file: "{{ item }}"
  loop:
    - caddy.yml
    - docker.yml

- name: install jenkins and casc
  include_tasks:
    file: install_jenkins.yml

- name: upload jenkins jobs and setup jobs configuration with docker
  include_tasks:
    file: jenkins_jobs.yml

- name: install and enable jenkins plugins
  include_tasks:
    file: jenkins_plugins.yml

- name: install kubectl and login to node with jenkins
  include_tasks:
    file: kubernetes.yml
