FROM gcc:11.2.0 as befunge
SHELL ["/bin/bash", "-c"]
WORKDIR /app
RUN git clone https://github.com/catseye/Befunge-93.git
RUN cd Befunge-93 && make

FROM alpine:3.17.2
COPY --from=befunge /app/Befunge-93/bin/bef /bin
ONBUILD COPY main.bf .
