- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker packages
  apt:
    name:
      - docker-ce
      - docker-compose
    state: latest
    update_cache: true

- name: Create caddy
  ansible.builtin.file:
    path: /app/caddy
    state: directory
    mode: '0755'

- name: Template Caddyfile
  ansible.builtin.template:
    src: files/Caddyfile.jinja
    dest: /app/caddy

- name: Install passlib
  pip:
    name: passlib

- name: create registry passwd
  community.general.htpasswd:
    path: /etc/registry_passwd
    name: "{{ registry_user }}"
    password: "{{ registry_passwd }}"
    owner: root
    mode: 0640

- name: Create and start services
  community.docker.docker_compose:
    project_name: whanos_registry
    definition:
      version: "3"
      services:
        registry:
          image: docker.io/registry
          volumes:
            - registry_data:/var/lib/registry
            - /etc/registry_passwd:/auth/htpasswd:ro
          environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
          ports:
            - 5000:5000
          restart: always
        caddy:
          image: caddy:2.6.2-alpine
          ports:
            - 443:443
            - 80:80
          volumes:
            - /app/caddy:/etc/caddy/
          restart: always
      volumes:
        registry_data: