- name: Docker repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: yum update
  yum:
    name: '*'
    state: latest

- name: Install docker and python
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3
      - python3-pip
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10

- name: install docker sdk python
  pip:
    name: "{{ item }}"
  loop:
    - docker
    - docker-compose

- name: start docker
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    state: started

- name: create dest dir for caddyfile mount
  file:
    path: /mnt/caddy
    state: directory

- name: Template Caddyfile
  ansible.builtin.template:
    src: files/Caddyfile.jinja
    dest: /mnt/caddy/Caddyfile
  register: caddyfile
  vars:
    registry_passwd_hash: "{{ registry_passwd | password_hash('bcrypt', 'Bs9KODXun8sMaq6t7s27XO') }}"

- name: Create and start services
  # when: caddyfile.changed
  community.docker.docker_compose:
    restarted: true
    project_name: whanos_registry
    definition:
      version: "3"
      services:
        registry:
          image: docker.io/registry
          volumes:
            - registry_data:/var/lib/registry
          environment:
            REGISTRY_HTTP_ADDR: 0.0.0.0:5000
          restart: always
          networks:
            - registry_network
        caddy:
          image: caddy:2.6.2-alpine
          ports:
            - 443:443
            - 80:80
          volumes:
            - /mnt/caddy:/etc/caddy/
            - caddy_data:/data
          restart: always
          networks:
            - registry_network
      volumes:
        registry_data:
        caddy_data:
      networks:
        registry_network: