version: "3"

services:
  registry:
    image: docker.io/registry
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - 443:5000
    restart: always

  caddy:
    image: caddy:2.6.2-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - /app/caddy:/etc/caddy/

volumes:
  registry_data: