- hosts: registry
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - role: registry
      tags: registry

- hosts: jenkins
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - role: jenkins
      tags: jenkins

# - hosts: k8
#   become: true
#   vars_files:
#     - ./vars.yml
#   roles:
#     - k8
